In [2]:
import numpy as np
#better than list bcz it is faster and takes less bytes of memory
import sys

# The Basics 

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a*b)

[ 4 10 18]


In [12]:
c = np.array([[23, 54, 12, 34], [50, 6, 4, 8]])
print(c)

[[23 54 12 34]
 [50  6  4  8]]


In [13]:
#get dimension
c.ndim

2

In [14]:
#get shape
c.shape

(2, 4)

In [15]:
#get type
c.dtype

dtype('int32')

In [16]:
#get size
c.itemsize

4

In [17]:
#get total size
c.size * c.itemsize #or c.nbytes

32

# Accessing/Changing specific elements, rows, columns

In [18]:
k = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(k)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
#get specific element [row, column]
k[0, 4]


5

In [21]:
#get a specific row
k[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
#get a specific column
k[:, 4]

array([ 5, 12])

In [23]:
k[0, 2] = 33
print(k)

[[ 1  2 33  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


# 3D example

In [28]:
d = np.array([[[1, 2], [4, 5]], [[7, 8], [10, 11]]])
print(d)

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [29]:
#get a sepcific element (work outside in)
d[0, 1, 0]

4

# Initializing different types of arrays

In [34]:
#all 0s matrix 
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [36]:
np.ones((2, 3, 6), dtype = 'int32')

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [39]:
#any other number
np.full((2,7), 31, dtype= 'float32')

array([[31., 31., 31., 31., 31., 31., 31.],
       [31., 31., 31., 31., 31., 31., 31.]], dtype=float32)

In [42]:
#random decimal numbers
np.random.rand(2,3)

array([[0.00944632, 0.56491644, 0.6267434 ],
       [0.38525889, 0.67783319, 0.5219813 ]])

In [47]:
#random int values
np.random.randint(-5, 3, size=(2, 5)) #3 это до трех

array([[-1, -1,  2, -3,  1],
       [-3,  1, -5,  1,  2]])

In [49]:
#Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
array = np.array([[1, 2, 3]])
rep = np.repeat(array, 5, axis=0)
print(rep)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
output = np.ones((5, 5))
print (output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Copying

In [60]:
h = np.array([12, 34, 56])
b = a.copy()
b[0] = 100
print(b)
print(h)

[100   2   3]
[12 34 56]


# MAth 

In [65]:
j = np.array([12, 34, 56])
j * 2
j + 4
j - 19
j // 2

array([ 6, 17, 28], dtype=int32)

In [66]:
l = np.array([10, 20, 30])
j+l

array([22, 54, 86])

In [68]:
#take the sin cos
np.sin(j)
np.cos(l)

array([-0.83907153,  0.40808206,  0.15425145])

# Linear algebra 

In [75]:
n = np.ones((2, 3))
print(n)

m = np.full((3, 2), 4)
print(m)

np.matmul(n, m)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]


array([[12., 12.],
       [12., 12.]])

In [76]:
#find the determinant 
v = np.identity(5)
np.linalg.det(v)

1.0

# Statistics

In [80]:
stats = np.array([[23, 54, 25], [34, 65, 87]])
np.min(stats, axis= 1)
np.max(stats, axis= 1)

array([54, 87])

In [82]:
np.sum(stats, axis=1) #if axis is 0 then it is going 
#to sum up the values in 2 lists, if axis is 1 within the one list

array([102, 186])

# Reorganizing arrays 

In [87]:
before = np.array([[23, 54, 25], [34, 65, 87]])
print(before)

after = before.reshape(2, 3)
print(after)

[[23 54 25]
 [34 65 87]]
[[23 54 25]
 [34 65 87]]


In [89]:
#vertically stocking
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])
np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [90]:
#horizontal stack
h1 = np.ones((2, 3))
h2 = np.zeros((2, 3))
np.hstack((h1, h2))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

# Miscellaneous 

In [ ]:
#load data from file
filedata = np.genfromtext('titleoffile.txt', delimiter= ',')
filedata.astype('int32')
filedata

# Advanced indexing

In [ ]:
filedata > 50